### ISSUE TITLE
iOS Version

### ISSUE THREAD

**Issue by Sammy990** [microsoft/WindowsAutopilotCompanion#1]
Hi, any plans to have a iOS version collection which can be build with a apple developer cert for inhouse distribution?

**Comment by mtniehaus** [comment]
The Xamarin project does support iOS, but we will leave it up to you to actually build it as we don’t have a Mac available to do that 😊

Thanks,
-Michael

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
[HxS - 18903 - 16.0.11629.20146]

________________________________

**Comment by Sammy990** [comment]
Excellet Michael! Thanks for the fast response
