### ISSUE TITLE
QR scan cannot utilise camera

### ISSUE THREAD

**Issue by Andy298** [microsoft/WindowsAutopilotCompanion#11]
Trying on Galaxy S10. Permission to camera allowed but just get a white box where the scanner should be.

**Comment by thbch** [comment]
> Trying on Galaxy S10. Permission to camera allowed but just get a white box where the scanner should be.

Same here, it worked before on the same device I'm using now, but currently no more...

**Comment by jgudmundson-RETSD** [comment]
Restart the app and it should work.  Same thing happened to me.

**Comment by Andy298** [comment]
> Restart the app and it should work. Same thing happened to me.

Yeah, tried and kept getting it. Oddly if I give the app permission to file system it works.
