### ISSUE TITLE
iOS Ressources missing

### ISSUE THREAD

**Issue by Sammy990** [microsoft/WindowsAutopilotCompanion#2]
Hi Michael, sorry to disturb.
By trying to build the project I encountered two issues:
1. AppIcon.appiconset is missing all the .png files requires for a successfull build/run. Only the json file reference is present.
2. The LaunchScreen.storyboard is also missing on the repository.

Could you kindly provide the missing files?

**Comment by mtniehaus** [comment]
I’ve added the missing files.  Can you try again?

Thanks,
-Michael

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
[HxS - 18903 - 16.0.11629.20146]

________________________________

**Comment by Sammy990** [comment]
Works great. Thanks Michael!

**Comment by mtniehaus** [comment]
Does this mean you successfully built, deployed, and used the iOS version?  (It would be great to get a confirmation of that.)

**Comment by Sammy990** [comment]
Absolutely! Worked like a charm. Good job.
