### ISSUE TITLE
Update tenant permissions and App Name

### ISSUE THREAD

**Issue by Sammy990** [microsoft/WindowsAutopilotCompanion#4]
After we can now build the app successfully, we've identified the app's name when authenticated to azure is "manojtestUWPApp1". Where in the project this can be modified to have another App Name when authenticated to Azure.

Also, we see the app asks for a lot of permissions at the tenant level, which are definitely not required for the operations inside the app (like Access user mailboxes etc.) it seems like it requests almost everything of available azure permissions. Could you kindly tighten the requested permission only to those really required? If you keep it as it is now, I'll get it never approved for production.

**Comment by mtniehaus** [comment]
Good feedback.  You could create your own app in Azure AD and use it instead of the applicationId value currently coded in the LogonViewModel.cs file:

            string applicationId = "4253c270-b756-4c48-9e28-8f202b6798ec";

We'll look into create a new app that has fewer rights.

**Comment by Sammy990** [comment]
Sounds great. Will create my own app in Azure, maybe you can post a list of rights really required once you figured out what is really needed.

One more UX related feedback. On the logon screen, when typing the tenant name there is no scaling of the page. Means the keyboard overlays the text input field so you aren’t able to see what you’re typing

**Comment by mtniehaus** [comment]
I've changed the application ID to the one used in the Intune script samples.  As far as rights needed, will work on that.  At a high level, it will read Azure AD device objects, Intune device objects, Autopilot registered device objects, Intune device category objects, and the Azure AD organization object.  It will write Intune device objects (to set a category) and Autopilot device objects (to assign a user and display name for that user).

**Comment by Sammy990** [comment]
Great! Will give it a try and rebuild on Monday.
Does it mean, the app will still request almost all rights at the tenant, or only the required to work correctly?

**Comment by mtniehaus** [comment]
I’m not sure what rights are associated with that app.  In my case, I had already allowed that app so I wasn’t prompted.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
[HxS - 18907 - 16.0.11629.20188]

________________________________

**Comment by Sammy990** [comment]
Looks god so far. Intune PowerShell App have enough permissions to work properly
