### ISSUE TITLE
QR Scan doesn‘t work

### ISSUE THREAD

**Issue by Sammy990** [microsoft/WindowsAutopilotCompanion#6]
At least on iOS, the QR code scan functionality doesn’t work. As what I can discover, the required permission requests to access camera doesn’t work as they’re simply not implemented. This could be solved by adding the Permissions.Plugin from NuGet and modifying some of the code structure and Info.plist

**Comment by mtniehaus** [comment]
I've added the Xamarin-recommended entries to Info.plist.  Can you try it again?

**Comment by Sammy990** [comment]
Adding the camera usage description in the Info.plist is required, however this will not solve the issue of missing code. When you run "Scan QR Code", it just displays a white background with a red line. But don't try to access the camera

**Comment by Sammy990** [comment]
![IMG_0280](https://user-images.githubusercontent.com/39421064/58541582-1c6a9700-81fc-11e9-97eb-b71683e20bd3.jpeg)

**Comment by mtniehaus** [comment]
There was a missing bar code initialization call in the iOS-specific code.  I’ve added that, but I don’t know if that’s sufficient to address the problem.  It should at least get us one step closer.

Thanks,
-Michael

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
[HxS - 18908 - 16.0.11629.20188]

________________________________

**Comment by Sammy990** [comment]
Works now! Thanks for the updated sources Michael!
