### ISSUE TITLE
Update App to support GroupTag and Rename Device

### ISSUE THREAD

**Issue by Sammy990** [microsoft/WindowsAutopilotCompanion#8]
Is it possible to update the app in order to support GroupTag editing and rename device functions within the app?

I also wanted to ask, if there are any plans to have this app being provided officially by Microsoft to IT Admins? We usually don't have time updating/compiling the apps, but highly rely on those to perform our daily business. A officially supported and provided App solution from the vendor would be a great improvement and would help speed up the adoption of AutoPilot technologies in enterprises.

**Comment by mtniehaus** [comment]
Already added group tag functionality.  There are no active plans to publish it to the Apple/Google stores, but we will consider it.
